spring.application.name=demo

#url del servidor y base datos - MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/tickets?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
spring.h2.console.enabled=false
#DDL
#create=borra la base datos si existe
#y crea la base datos cuando se ejecuta el servicio
#create-drop=borra la base datos si existe
#y crea la base datos cuando se ejecuta el servicio
#y se elimina cuando se detiene el servicio
#update=verifica la base datos si es distinta al modelo la actualiza
#actualiza la estructura
#none=no ejecutará DDL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.connection.timezone=UTC
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false


server.port=8080

## Configuración de correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=juliannaranjo58@gmail.com
spring.mail.password=ywgi ukdw uenj rsic
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Debe tener al menos 64 bytes (ejemplo generado aleatoriamente)
jwt.secret=q2CFZJQrPNHMtp4cFdLVOLqlt1wqnw8/ykToDaisOJf7JO+XvT/c7Orka5MOACC7rvf9Wkz7gfVU1EeqayZBhQ==

# Configuración de archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true